### ISSUE TITLE
对document需要有最小粒度的控制，求老司机指导

### ISSUE THREAD

**Issue by hd925** [milkfr/ATField#2]
在我厂的一个小项目中需要实现类似的RBAC权限控制，我使用的也是这套类似的方案，但是不如老司机的方案来的优雅，但是功能还是发现有缺失，比如有10个文档，需要对用户XX授予只能访问1，但是可以删除2,3这种情况，用我的方法后发现这种方案不能继承，也就是说资源和功能和用户这三种还不能做到绑定，如果对文档2.3授予了删除的权限，文档1的话也有这个权限

求老司机指导，如何才能将用户，资源和功能完美的结合？ 谢谢

**Comment by franciumzh** [comment]
不好意思，很久没有登录了，不知道问题解决没有
我只是信息安全专业今年刚毕业的学生，这个也只是学生时候学习做的Demo，不是老司机哈
一般来讲，我们把权限分为水平权限和垂直权限，RBAC多用于垂直权限控制，用户角色和功能对应。
而document这种资源访问一般涉及的是同权限角色间水平方向上的权限控制
看了你的描述，我感觉问题在于：
1、document是一种资源，数量众多，不能单独划分为功能，不像功能一样可以在代码API接口用装饰器限定访问角色
2、用户权限复杂，用户ABCD权限属于同一层级，但是对单个资源上有用不同限制，这就可能属于水平权限问题，像论坛网站网友权限一样都有文章编辑查看删除权限，但编辑删除权限只属于作者才有，当可以多人编辑时这种情况更加复杂
我感觉解决方案可以有以下一些
1、水平权限问题可能不能用我这种框架上为每一个handler添加装饰器的方式，因为将每篇文档作为一个功能的话，功能数量太多，当然也可以改框架将功能设置为动态生成，但管理员就不好控制功能分配
2、类似Linux系统的权限ACL表，为document设置所有者所有组的ACL表，设置掩码作为一般情况，提供修改所有者所有组和ACL权限的接口，这就需要了解一下Linux的权限机制了
